export const FETCH_PRODUCTS = "FETCH_PRODUCTS"

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const CHANGE_SELECTED = 'CHANGE_SELECTED'
export const CHANGE_SELECTED_ALL = 'CHANGE_SELECTED_ALL'
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY'